VERSION_MAPPING_DICT = {
    "Red": "red",
    "Blue": "blue",
    "Yellow": "yellow",
    "Gold": "gold",
    "Silver": "silver",
    "Crystal": "crystal",
    "Ruby": "ruby",
    "Sapphire": "sapphire",
    "Emerald": "emerald",
    "FireRed": "firered",
    "LeafGreen": "leafgreen",
    "Diamond": "diamond",
    "Pearl": "pearl",
    "Platinum": "platinum",
    "HeartGold": "heartgold",
    "SoulSilver": "soulsilver",
    "Black": "black",
    "White": "white",
    "Colosseum": "colosseum",
    "XD": "xd",
    "Black 2": "black-2",
    "White 2": "white-2",
    "X": "x",
    "Y": "y",
    "Omega Ruby": "omega-ruby",
    "Alpha Sapphire": "alpha-sapphire",
    "Sun": "sun",
    "Moon": "moon",
    "Ultra Sun": "ultra-sun",
    "Ultra Moon": "ultra-moon",
    "Let's Go Pikachu": "lets-go-pikachu",
    "Let's Go Eevee": "lets-go-eevee",
    "Sword": "sword",
    "Shield": "shield",
    "The Isle of Armor": "the-isle-of-armor",
    "The Crown Tundra": "the-crown-tundra",
    "Brilliant Diamond": "brilliant-diamond",
    "Shining Pearl": "shining-pearl",
    "Legends: Arceus": "legends-arceus",
    "Legends: Z-A": "legends-z-a",
    "Scarlet": "scarlet",
    "Violet": "violet",
    "The Teal Mask": "the-teal-mask",
    "The Indigo Disk": "the-indigo-disk",
}

REVERSED_MAPPING_DICT = {
    "red": "Red",
    "blue": "Blue",
    "yellow": "Yellow",
    "gold": "Gold",
    "silver": "Silver",
    "crystal": "Crystal",
    "ruby": "Ruby",
    "sapphire": "Sapphire",
    "emerald": "Emerald",
    "firered": "FireRed",
    "leafgreen": "LeafGreen",
    "diamond": "Diamond",
    "pearl": "Pearl",
    "platinum": "Platinum",
    "heartgold": "HeartGold",
    "soulsilver": "SoulSilver",
    "black": "Black",
    "white": "White",
    "colosseum": "Colosseum",
    "xd": "XD",
    "black-2": "Black 2",
    "white-2": "White 2",
    "x": "X",
    "y": "Y",
    "omega-ruby": "Omega Ruby",
    "alpha-sapphire": "Alpha Sapphire",
    "sun": "Sun",
    "moon": "Moon",
    "ultra-sun": "Ultra Sun",
    "ultra-moon": "Ultra Moon",
    "lets-go-pikachu": "Let's Go Pikachu",
    "lets-go-eevee": "Let's Go Eevee",
    "sword": "Sword",
    "shield": "Shield",
    "the-isle-of-armor": "The Isle of Armor",
    "the-crown-tundra": "The Crown Tundra",
    "brilliant-diamond": "Brilliant Diamond",
    "shining-pearl": "Shining Pearl",
    "legends-arceus": "Legends: Arceus",
    "legends-z-a": "Legends: Z-A",
    "scarlet": "Scarlet",
    "violet": "Violet",
    "the-teal-mask": "The Teal Mask",
    "the-indigo-disk": "The Indigo Disk",
}
