# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Format and Test

on:  push

permissions:
  contents: read

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Setup Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.11
    - name: Setup Poetry
      uses: abatilo/actions-poetry@v2
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        poetry install
    - name: Run Black
      run: |
        python -m pip install black
        black .
    - name: Run PyTest
      run: poetry run pytest
